CREATE DATABASE NIMBUS_CONF;

########################################################################################################

CREATE TABLE NIMBUS_CONF.CONF
(
	CID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	OWNER INT UNSIGNED NOT NULL,
	NAME NVARCHAR(41) NOT NULL,
	URL NVARCHAR(21) NOT NULL,
	IMG MEDIUMBLOB,
	IMG_UP DATETIME,
	BANNER MEDIUMBLOB,
	BANNER_UP DATETIME,
	COUN INT UNSIGNED NOT NULL,
	PROV INT UNSIGNED NOT NULL,
	CITY INT UNSIGNED NOT NULL,
	DIST INT UNSIGNED,
	ADDR NVARCHAR(41),
	FADDR NVARCHAR(61) NOT NULL,
	STIME DATETIME NOT NULL,
	REGISTRATION ENUM('O', 'C') NOT NULL,
	SEARCH ENUM('Y', 'N') NOT NULL,
	ETIME DATETIME,
	STATUS ENUM('D', 'P', 'C') NOT NULL,
	DESCRIPTION MEDIUMTEXT,
	CTIME DATETIME NOT NULL,
	LAT DECIMAL(12,8),
	LNG DECIMAL(12,8),

	PRIMARY KEY (CID),
	FOREIGN KEY (OWNER) REFERENCES NIMBUS_USER.USER (UID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE UNIQUE INDEX URL_INDEX ON NIMBUS_CONF.CONF (URL(20));
CREATE INDEX NAME_INDEX ON NIMBUS_CONF.CONF (NAME(40));
CREATE INDEX COUN_INDEX ON NIMBUS_CONF.CONF (COUN);
CREATE INDEX PROV_INDEX ON NIMBUS_CONF.CONF (PROV);
CREATE INDEX CITY_INDEX ON NIMBUS_CONF.CONF (CITY);
CREATE INDEX DIST_INDEX ON NIMBUS_CONF.CONF (DIST);
CREATE INDEX REGISTRATION_INDEX ON NIMBUS_CONF.CONF (REGISTRATION);
CREATE INDEX SEARCH_INDEX ON NIMBUS_CONF.CONF (SEARCH);
CREATE INDEX STATUS_INDEX ON NIMBUS_CONF.CONF (STATUS);
CREATE INDEX FADDR_INDEX ON NIMBUS_CONF.CONF (FADDR(60));
CREATE INDEX LAT_INDEX ON NIMBUS_CONF.CONF (LAT);
CREATE INDEX LNG_INDEX ON NIMBUS_CONF.CONF (LNG);

########################################################################################################

CREATE TABLE NIMBUS_CONF.SCHE
(
	SID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	CID INT UNSIGNED NOT NULL,
	UID INT UNSIGNED NOT NULL,
	DATE DATE NOT NULL,
	STIME TIME NOT NULL,
	ETIME TIME NOT NULL,
	LOCATION NVARCHAR(101) NOT NULL,
	SUMMARY NVARCHAR(101) NOT NULL,
	NOTE TEXT,

	PRIMARY KEY (SID),
	FOREIGN KEY (UID) REFERENCES NIMBUS_USER.USER (UID),
	FOREIGN KEY (CID) REFERENCES NIMBUS_CONF.CONF (CID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

########################################################################################################

CREATE TABLE NIMBUS_CONF.SPON
(
	SID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	CID INT UNSIGNED NOT NULL,
	CNAME NVARCHAR(41) NOT NULL,
	URL NVARCHAR(41),
	IMG MEDIUMBLOB,

	PRIMARY KEY (SID),	
	UNIQUE (CID, CNAME),
	FOREIGN KEY (CID) REFERENCES NIMBUS_CONF.CONF (CID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE INDEX CNAME_INDEX ON NIMBUS_CONF.SPON (CNAME(40));

########################################################################################################

CREATE TABLE NIMBUS_CONF.RELA
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	UID INT UNSIGNED NOT NULL,
	CID INT UNSIGNED NOT NULL,
	ROLE ENUM('A', 'S') NOT NULL,

	PRIMARY KEY (ID),
	UNIQUE (CID, UID, ROLE),
	FOREIGN KEY (UID) REFERENCES NIMBUS_USER.USER (UID),
	FOREIGN KEY (CID) REFERENCES NIMBUS_CONF.CONF (CID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

########################################################################################################

GRANT ALL ON NIMBUS_CONF.* TO aconf@'%' IDENTIFIED BY 'aconfpass';
FLUSH PRIVILEGES;